"""Add to model User email and avatar

Revision ID: fe7285819a93
Revises: c24506ece4d5
Create Date: 2025-04-06 11:46:33.059133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe7285819a93"
down_revision: Union[str, None] = "c24506ece4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET confirmed = true WHERE confirmed IS NULL")
    op.alter_column("users", "confirmed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
